-- menu init
INSERT INTO T_MENU (TEXT,ADDR,PID,CREATETIME,LASTMODIFYTIME) VALUES ('子系统1','',0,NOW(),NOW());
  INSERT INTO T_MENU (TEXT,ADDR,PID,CREATETIME,LASTMODIFYTIME) SELECT '子系统1-1','',ID,NOW(),NOW() FROM T_MENU WHERE TEXT= '子系统1';
    INSERT INTO T_MENU (TEXT,ADDR,SERVICENAME,PID,CREATETIME,LASTMODIFYTIME) SELECT '子系统1-1-1','','ffzl_base_menu',ID,NOW(),NOW() FROM T_MENU WHERE TEXT= '子系统1-1';
    INSERT INTO T_MENU (TEXT,ADDR,SERVICENAME,PID,CREATETIME,LASTMODIFYTIME) SELECT '子系统1-1-2','','ffzl_base_menu',ID,NOW(),NOW() FROM T_MENU WHERE TEXT= '子系统1-1';
  INSERT INTO T_MENU (TEXT,ADDR,PID,CREATETIME,LASTMODIFYTIME) SELECT '子系统1-2','',ID,NOW(),NOW() FROM T_MENU WHERE TEXT= '子系统1';
    INSERT INTO T_MENU (TEXT,ADDR,PID,CREATETIME,LASTMODIFYTIME) SELECT '子系统1-2-1','',ID,NOW(),NOW() FROM T_MENU WHERE TEXT= '子系统1-2';
    INSERT INTO T_MENU (TEXT,ADDR,PID,CREATETIME,LASTMODIFYTIME) SELECT '子系统1-2-2','',ID,NOW(),NOW() FROM T_MENU WHERE TEXT= '子系统1-2';
  INSERT INTO T_MENU (TEXT,ADDR,PID,CREATETIME,LASTMODIFYTIME) SELECT '子系统1-3','',ID,NOW(),NOW() FROM T_MENU WHERE TEXT= '子系统1';
INSERT INTO T_MENU (TEXT,ADDR,PID,CREATETIME,LASTMODIFYTIME) VALUES ('子系统2','',0,NOW(),NOW());
