CREATE TABLE T_Users(
  `ID` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `USERNAME` VARCHAR(64) NOT NULL DEFAULT "" COMMENT '用户名',
  `PASSWORD` VARCHAR(64) NOT NULL DEFAULT "" COMMENT '密码',
  `SALT` BIGINT NOT NULL DEFAULT  0 COMMENT '盐值',
  `CREATETIME` DATETIME NOT NULL DEFAULT '1990-01-01' COMMENT '创建时间',
  `LASTMODIFYTIME` DATETIME NOT NULL DEFAULT '1990-01-01' COMMENT '最后修改时间'
)ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T_MENU;
CREATE TABLE T_MENU(
  `ID`  BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `TEXT` VARCHAR(32) NOT NULL DEFAULT '菜单' COMMENT '菜单名称',
  `ADDR` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '菜单地址',
  `PID`  BIGINT NOT NULL DEFAULT 0  COMMENT '父节点ID',
  `CREATETIME` DATETIME NOT NULL DEFAULT '1990-01-01' COMMENT '创建时间',
  `LASTMODIFYTIME` DATETIME NOT NULL DEFAULT '1990-01-01' COMMENT '最后修改时间'
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;
